num_epochs: 2
warmup_steps: 50
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
weight_decay: 0.01
logging_steps: 1
evaluation_strategy: epoch
eval_steps: 1
save_steps: 1
gradient_accumulation_steps: 4
gradient_checkpointing: True
optim: adamw_bnb_8bit
